'package: arktype-adapter':
  - changed-files:
      - any-glob-to-any-file: 'packages/arktype-adapter/**/*'
'package: directive-functions-plugin':
  - changed-files:
      - any-glob-to-any-file: 'packages/directive-functions-plugin/**/*'
'package: eslint-plugin-router':
  - changed-files:
      - any-glob-to-any-file: 'packages/eslint-plugin-router/**/*'
'package: history':
  - changed-files:
      - any-glob-to-any-file: 'packages/history/**/*'
'package: react-router':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-router/**/*'
'package: react-router-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-router-devtools/**/*'
'package: react-router-with-query':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-router-with-query/**/*'
'package: react-start':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-start/**/*'
'package: react-start-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-start-client/**/*'
'package: react-start-plugin':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-start-plugin/**/*'
'package: react-start-server':
  - changed-files:
      - any-glob-to-any-file: 'packages/react-start-server/**/*'
'package: router-cli':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-cli/**/*'
'package: router-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-core/**/*'
'package: router-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-devtools/**/*'
'package: router-devtools-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-devtools-core/**/*'
'package: router-generator':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-generator/**/*'
'package: router-plugin':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-plugin/**/*'
'package: router-utils':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-utils/**/*'
'package: router-vite-plugin':
  - changed-files:
      - any-glob-to-any-file: 'packages/router-vite-plugin/**/*'
'package: server-functions-plugin':
  - changed-files:
      - any-glob-to-any-file: 'packages/server-functions-plugin/**/*'
'package: solid-router':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-router/**/*'
'package: solid-router-devtools':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-router-devtools/**/*'
'package: solid-start':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-start/**/*'
'package: solid-start-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-start-client/**/*'
'package: solid-start-plugin':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-start-plugin/**/*'
'package: solid-start-server':
  - changed-files:
      - any-glob-to-any-file: 'packages/solid-start-server/**/*'
'package: start-client-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-client-core/**/*'
'package: start-plugin-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-plugin-core/**/*'
'package: start-server-core':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-server-core/**/*'
'package: start-server-functions-client':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-server-functions-client/**/*'
'package: start-server-functions-fetcher':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-server-functions-fetcher/**/*'
'package: start-server-functions-server':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-server-functions-server/**/*'
'package: start-storage-context':
  - changed-files:
      - any-glob-to-any-file: 'packages/start-storage-context/**/*'
'package: valibot-adapter':
  - changed-files:
      - any-glob-to-any-file: 'packages/valibot-adapter/**/*'
'package: virtual-file-routes':
  - changed-files:
      - any-glob-to-any-file: 'packages/virtual-file-routes/**/*'
'package: zod-adapter':
  - changed-files:
      - any-glob-to-any-file: 'packages/zod-adapter/**/*'
'documentation':
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
