# Setup taken from https://codspeed.io/docs/benchmarks/nodejs/vitest
name: Client Nav Benchmarks

on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read # required for actions/checkout
  id-token: write # required for OIDC authentication with CodSpeed

env:
  NX_CLOUD_ACCESS_TOKEN: ${{ secrets.NX_CLOUD_ACCESS_TOKEN }}
  SERVER_PRESET: 'node-server'

jobs:
  client-nav-benchmarks:
    name: Run Client Nav Benchmarks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.1

      - name: Setup Tools
        uses: tanstack/config/.github/setup@main

      - name: Run Benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: WITH_INSTRUMENTATION=1 pnpm nx run @benchmarks/client-nav:test:perf:react

      - name: Run Benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: WITH_INSTRUMENTATION=1 pnpm nx run @benchmarks/client-nav:test:perf:solid

      - name: Run Benchmarks with CodSpeed
        uses: CodSpeedHQ/action@v4
        with:
          mode: simulation
          run: WITH_INSTRUMENTATION=1 pnpm nx run @benchmarks/client-nav:test:perf:vue
